### ISSUE TITLE
Eclipse install issues

### ISSUE THREAD

**Issue by cajturner** [orcc/orcc#143]
I have been trying to install orcc using the getting started tutorial: http://orcc.sourceforge.net/getting-started/install-orcc/.
I installed orcc but I am receiving the following error.  I receive this error on Mac and Windows.

```org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/HelloOrcc/src/org/tutorial/hellorcc/Hello.cal'.```
Stack Trace:
```java.lang.NullPointerException
	at net.sf.orcc.cal.generator.CalGenerator.serialize(CalGenerator.java:207)
	at net.sf.orcc.cal.generator.CalGenerator.doGenerate(CalGenerator.java:168)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:45)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:34)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:564)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:549)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:534)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:280)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
	at net.sf.orcc.cal.ui.builder.CalBuilder.build(CalBuilder.java:57)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Other details:
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_65
I installed a fresh version of eclipse neon.2

Cheers!

**Comment by casalebrunet** [comment]
Hi @cajturner 
Could you try to install the plugins from http://orcc.sourceforge.net/eclipse/nightly/ and let me know, please?

**Comment by cajturner** [comment]
Hello @casalebrunet,
That has done the trick. Many thanks!
