### ISSUE TITLE
does not appear to work in eclipse 4.7

### ISSUE THREAD

**Issue by Bazmundi** [orcc/orcc#144]
Installed orcc 2.3xxx into a rodin 3 IDE based upon eclipse 4.7.2.

Downloaded example apps.

Imported HelloWorld to find the following against all files:

null - See error log for details	Math.cal	/System/src/std/util	line 1	Xtext Check (normal)

I then imported System since it appeared System might be a dependency given its description but same same.

I tried running the supplied Hello.xdf to get the following error:
Visitor interpreter and debugger simulation error: null

The Hello.xdf file was assigned as the input stimulus file by default by the wizard.  There was no obvious VALIDATE checkbox or prompt.  

The log under D:\rodin3\rodin\configuration reports:

!SESSION 2018-03-12 08:40:10.747 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_AU
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2018-03-12 08:40:14.114
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
	at org.eclipse.swt.internal.C.<clinit>(C.java:16)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:140)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:765)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:160)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:181)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by robstewart57** [comment]
@Bazmundi hi, can this issue be closed now?

**Comment by ReaddyEddy** [comment]
No dialog raised on Set/Update Refinement seen in eclipse 4.6 and eclipse 4.7 on new project based on Add example. 
Also importing orc-apps AddArray shows invalid refinement on existing actor instances. 
<img width="1580" alt="topaddarray" src="https://user-images.githubusercontent.com/3310960/40356711-d3cf32b8-5db1-11e8-8a9d-09f5f32e39fc.png">
